// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tarot} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistoryRecord(arg1:number):Promise<void>;

export function DrawCard():Promise<tarot.DrawnCard>;

export function DrawCards(arg1:number):Promise<Array<tarot.DrawnCard>>;

export function DrawSpread(arg1:string,arg2:string):Promise<tarot.SpreadResult>;

export function FullDeck():Promise<Array<tarot.Card>>;

export function GetAboutTarot():Promise<Array<tarot.GuideSection>>;

export function GetDailyAnimation():Promise<tarot.DailyAnimation>;

export function GetDailyCard():Promise<tarot.DailyCard>;

export function GetGuide():Promise<Array<tarot.GuideSection>>;

export function GetHistory():Promise<Array<tarot.HistoryRecord>>;

export function GetLastHistory(arg1:number):Promise<Array<tarot.HistoryRecord>>;

export function GetLegal():Promise<tarot.LegalDocs>;

export function GetQuestions():Promise<Array<tarot.QuestionCategory>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSpreads():Promise<Array<tarot.Spread>>;

export function Greet(arg1:string):Promise<string>;

export function HistoryCount():Promise<number>;

export function LastSpread():Promise<tarot.Spread>;

export function RemainingCards():Promise<number>;

export function RemainingCardsList():Promise<Array<tarot.Card>>;

export function ResetDailyCard():Promise<void>;

export function ResetDeck():Promise<string>;

export function Shuffle():Promise<string>;

export function Status():Promise<Record<string, any>>;

export function Today():Promise<string>;

export function UpdateHistoryComment(arg1:number,arg2:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
