// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function DrawCard() {
  return window['go']['main']['App']['DrawCard']();
}

export function DrawCards(arg1) {
  return window['go']['main']['App']['DrawCards'](arg1);
}

export function DrawSpread(arg1, arg2) {
  return window['go']['main']['App']['DrawSpread'](arg1, arg2);
}

export function FullDeck() {
  return window['go']['main']['App']['FullDeck']();
}

export function GetAboutTarot() {
  return window['go']['main']['App']['GetAboutTarot']();
}

export function GetDailyAnimation() {
  return window['go']['main']['App']['GetDailyAnimation']();
}

export function GetDailyCard() {
  return window['go']['main']['App']['GetDailyCard']();
}

export function GetGuide() {
  return window['go']['main']['App']['GetGuide']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLastHistory(arg1) {
  return window['go']['main']['App']['GetLastHistory'](arg1);
}

export function GetLegal() {
  return window['go']['main']['App']['GetLegal']();
}

export function GetQuestions() {
  return window['go']['main']['App']['GetQuestions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpreads() {
  return window['go']['main']['App']['GetSpreads']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HistoryCount() {
  return window['go']['main']['App']['HistoryCount']();
}

export function LastSpread() {
  return window['go']['main']['App']['LastSpread']();
}

export function RemainingCards() {
  return window['go']['main']['App']['RemainingCards']();
}

export function RemainingCardsList() {
  return window['go']['main']['App']['RemainingCardsList']();
}

export function ResetDailyCard() {
  return window['go']['main']['App']['ResetDailyCard']();
}

export function ResetDeck() {
  return window['go']['main']['App']['ResetDeck']();
}

export function Shuffle() {
  return window['go']['main']['App']['Shuffle']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Today() {
  return window['go']['main']['App']['Today']();
}

export function UpdateHistoryComment(arg1, arg2) {
  return window['go']['main']['App']['UpdateHistoryComment'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
